# Generated by Django 5.2.7 on 2025-10-28 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0001_initial'),
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='dealactivity',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='deals.deal'),
        ),
        migrations.AddField(
            model_name='dealactivity',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='dealforecast',
            unique_together={('period_type', 'period_start', 'period_end')},
        ),
        migrations.AddField(
            model_name='dealproduct',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='deals.deal'),
        ),
        migrations.AlterUniqueTogether(
            name='dealstage',
            unique_together={('name', 'order')},
        ),
        migrations.AddField(
            model_name='salespipeline',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salespipeline',
            name='stages',
            field=models.ManyToManyField(related_name='pipelines', to='deals.dealstage'),
        ),
    ]
