# Generated by Django 5.2.7 on 2025-10-28 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('win_probability', 'Win Probability'), ('close_prediction', 'Close Date Prediction'), ('risk_assessment', 'Risk Assessment'), ('upsell_opportunity', 'Upsell Opportunity'), ('competitor_analysis', 'Competitor Analysis')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('confidence_score', models.PositiveIntegerField(default=0)),
                ('predicted_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('predicted_close_date', models.DateTimeField(blank=True, null=True)),
                ('risk_factors', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Deal Insight',
                'verbose_name_plural': 'Deal Insights',
                'db_table': 'deal_insights',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('kpi_type', models.CharField(choices=[('sales', 'Sales'), ('marketing', 'Marketing'), ('customer', 'Customer'), ('financial', 'Financial'), ('operational', 'Operational')], max_length=20)),
                ('formula', models.TextField()),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(default='count', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'KPI',
                'verbose_name_plural': 'KPIs',
                'db_table': 'kpis',
            },
        ),
        migrations.CreateModel(
            name='KPIMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'KPI Measurement',
                'verbose_name_plural': 'KPI Measurements',
                'db_table': 'kpi_measurements',
            },
        ),
        migrations.CreateModel(
            name='LeadInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('scoring', 'Lead Scoring'), ('qualification', 'Qualification Analysis'), ('conversion_prediction', 'Conversion Prediction'), ('timing', 'Optimal Timing'), ('channel_preference', 'Channel Preference')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('confidence_score', models.PositiveIntegerField(default=0)),
                ('score_breakdown', models.JSONField(default=dict)),
                ('recommendations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lead Insight',
                'verbose_name_plural': 'Lead Insights',
                'db_table': 'lead_insights',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictiveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('model_type', models.CharField(choices=[('churn_prediction', 'Churn Prediction'), ('lead_scoring', 'Lead Scoring'), ('deal_forecasting', 'Deal Forecasting'), ('upsell_prediction', 'Upsell Prediction'), ('sentiment_analysis', 'Sentiment Analysis'), ('customer_lifetime_value', 'Customer Lifetime Value')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('training_data_size', models.PositiveIntegerField(blank=True, null=True)),
                ('last_trained', models.DateTimeField(blank=True, null=True)),
                ('parameters', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Predictive Model',
                'verbose_name_plural': 'Predictive Models',
                'db_table': 'predictive_models',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('sales', 'Sales Report'), ('marketing', 'Marketing Report'), ('customer', 'Customer Report'), ('financial', 'Financial Report'), ('custom', 'Custom Report')], max_length=20)),
                ('query', models.TextField()),
                ('parameters', models.JSONField(default=dict)),
                ('filters', models.JSONField(default=dict)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('schedule_cron', models.CharField(blank=True, max_length=100)),
                ('recipients', models.JSONField(default=list)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'reports',
            },
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('parameters', models.JSONField(default=dict)),
                ('result_data', models.JSONField(blank=True, default=dict, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('execution_time', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Report Execution',
                'verbose_name_plural': 'Report Executions',
                'db_table': 'report_executions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('email', 'Email'), ('call', 'Phone Call'), ('chat', 'Live Chat'), ('survey', 'Survey'), ('social', 'Social Media'), ('review', 'Review')], max_length=20)),
                ('content', models.TextField()),
                ('sentiment_score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('sentiment_label', models.CharField(max_length=20)),
                ('confidence', models.PositiveIntegerField(default=0)),
                ('keywords', models.JSONField(default=list)),
                ('emotions', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sentiment Analysis',
                'verbose_name_plural': 'Sentiment Analyses',
                'db_table': 'sentiment_analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widgets', models.JSONField(default=list)),
                ('filters', models.JSONField(default=dict)),
                ('refresh_interval', models.PositiveIntegerField(default=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_dashboard', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analytics Dashboard',
                'verbose_name_plural': 'Analytics Dashboards',
                'db_table': 'analytics_dashboards',
            },
        ),
        migrations.CreateModel(
            name='CustomerInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('behavior', 'Behavior Analysis'), ('segmentation', 'Segmentation'), ('churn_prediction', 'Churn Prediction'), ('upsell_opportunity', 'Upsell Opportunity'), ('satisfaction', 'Satisfaction Analysis'), ('engagement', 'Engagement Analysis')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('confidence_score', models.PositiveIntegerField(default=0)),
                ('data_points', models.JSONField(default=dict)),
                ('recommendations', models.JSONField(default=list)),
                ('is_actionable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Customer Insight',
                'verbose_name_plural': 'Customer Insights',
                'db_table': 'customer_insights',
                'ordering': ['-created_at'],
            },
        ),
    ]
