# Generated by Django 5.2.7 on 2025-10-28 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealinsight',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='deals.deal'),
        ),
        migrations.AddField(
            model_name='kpimeasurement',
            name='kpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='analytics.kpi'),
        ),
    ]
